
name: 'vitest test'
on: pull_request
jobs:
  Component-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 19
      - uses: actions/cache@v4
        with:
         path: node_modules
         key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
         restore-keys: |
           ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: run vitest
        run: npm run test
